# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0, help_text='Pontos disponíveis para resgate', verbose_name='saldo de pontos')),
                ('lifetime_points', models.IntegerField(default=0, help_text='Total de pontos já acumulados (nunca decresce)', verbose_name='pontos acumulados')),
                ('stamps_current', models.IntegerField(default=0, help_text='Carimbos na cartela atual', verbose_name='carimbos atuais')),
                ('stamps_target', models.IntegerField(default=10, help_text='Carimbos necessários para o prêmio', verbose_name='meta de carimbos')),
                ('stamps_completed', models.IntegerField(default=0, help_text='Total de cartelas já completadas', verbose_name='cartelas completas')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Prata'), ('gold', 'Ouro'), ('platinum', 'Platina')], default='bronze', max_length=20, verbose_name='nível')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrito em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='guestman.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'conta de fidelidade',
                'verbose_name_plural': 'contas de fidelidade',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Acúmulo'), ('redeem', 'Resgate'), ('adjust', 'Ajuste'), ('expire', 'Expiração'), ('stamp', 'Carimbo')], max_length=20, verbose_name='tipo')),
                ('points', models.IntegerField(help_text='Positivo para acúmulo, negativo para resgate/expiração', verbose_name='pontos')),
                ('balance_after', models.IntegerField(help_text='Saldo de pontos após esta transação', verbose_name='saldo após')),
                ('description', models.CharField(help_text='Motivo da transação', max_length=200, verbose_name='descrição')),
                ('reference', models.CharField(blank=True, help_text='ID externo (ex: order:123)', max_length=100, verbose_name='referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='criado por')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='guestman_loyalty.loyaltyaccount', verbose_name='conta')),
            ],
            options={
                'verbose_name': 'transação de fidelidade',
                'verbose_name_plural': 'transações de fidelidade',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='guestman_lo_account_59a308_idx')],
            },
        ),
    ]
