# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], db_index=True, max_length=20, verbose_name='canal')),
                ('status', models.CharField(choices=[('opted_in', 'Opt-in'), ('opted_out', 'Opt-out'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='status')),
                ('legal_basis', models.CharField(choices=[('consent', 'Consentimento'), ('legitimate_interest', 'Interesse legítimo'), ('contract', 'Execução de contrato'), ('legal_obligation', 'Obrigação legal')], default='consent', help_text='Base legal LGPD para o tratamento de dados', max_length=30, verbose_name='base legal')),
                ('source', models.CharField(blank=True, help_text='Como o consentimento foi coletado (checkout, form, whatsapp)', max_length=100, verbose_name='origem')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP no momento do consentimento', null=True, verbose_name='endereço IP')),
                ('consented_at', models.DateTimeField(blank=True, help_text='Data/hora do opt-in', null=True, verbose_name='consentido em')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Data/hora do opt-out', null=True, verbose_name='revogado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='guestman.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'consentimento de comunicação',
                'verbose_name_plural': 'consentimentos de comunicação',
                'ordering': ['channel'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'channel'), name='guestman_unique_consent_per_channel')],
            },
        ),
    ]
