# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MergeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_ref', models.CharField(max_length=50)),
                ('target_ref', models.CharField(max_length=50)),
                ('source_id', models.UUIDField()),
                ('target_id', models.UUIDField()),
                ('actor', models.CharField(blank=True, max_length=200)),
                ('evidence', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('reverted', 'Reverted')], default='completed', max_length=20)),
                ('snapshot', models.JSONField(default=dict, help_text='PKs of migrated records by category, for undo.')),
                ('migrated_contact_points', models.PositiveIntegerField(default=0)),
                ('migrated_external_identities', models.PositiveIntegerField(default=0)),
                ('migrated_identifiers', models.PositiveIntegerField(default=0)),
                ('migrated_addresses', models.PositiveIntegerField(default=0)),
                ('migrated_preferences', models.PositiveIntegerField(default=0)),
                ('migrated_consents', models.PositiveIntegerField(default=0)),
                ('migrated_timeline_events', models.PositiveIntegerField(default=0)),
                ('loyalty_merged', models.BooleanField(default=False)),
                ('merged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-merged_at'],
                'indexes': [models.Index(fields=['source_ref'], name='guestman_merge_src_ref'), models.Index(fields=['target_ref'], name='guestman_merge_tgt_ref')],
            },
        ),
    ]
