# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0, verbose_name='total de pedidos')),
                ('total_spent_q', models.BigIntegerField(default=0, help_text='Total gasto em centavos', verbose_name='total gasto (centavos)')),
                ('average_ticket_q', models.BigIntegerField(default=0, help_text='Ticket médio em centavos', verbose_name='ticket médio (centavos)')),
                ('first_order_at', models.DateTimeField(blank=True, null=True, verbose_name='primeiro pedido em')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='último pedido em')),
                ('days_since_last_order', models.IntegerField(blank=True, null=True, verbose_name='dias desde último pedido')),
                ('average_days_between_orders', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='média de dias entre pedidos')),
                ('preferred_weekday', models.IntegerField(blank=True, help_text='0=Segunda, 6=Domingo', null=True, verbose_name='dia da semana preferido')),
                ('preferred_hour', models.IntegerField(blank=True, help_text='Hora preferida (0-23)', null=True, verbose_name='hora preferida')),
                ('favorite_products', models.JSONField(default=list, help_text='Lista de {sku, nome, qtd, ultimo_pedido}', verbose_name='produtos favoritos')),
                ('preferred_channel', models.CharField(blank=True, max_length=50, verbose_name='canal preferido')),
                ('channels_used', models.JSONField(default=list, help_text='Lista de canais utilizados', verbose_name='canais utilizados')),
                ('rfm_recency', models.IntegerField(blank=True, help_text='Score de recência RFM (1-5)', null=True, verbose_name='RFM recência')),
                ('rfm_frequency', models.IntegerField(blank=True, help_text='Score de frequência RFM (1-5)', null=True, verbose_name='RFM frequência')),
                ('rfm_monetary', models.IntegerField(blank=True, help_text='Score monetário RFM (1-5)', null=True, verbose_name='RFM monetário')),
                ('rfm_segment', models.CharField(blank=True, help_text="Segmento RFM (ex: 'campeão', 'em_risco', 'novo')", max_length=50, verbose_name='segmento RFM')),
                ('churn_risk', models.DecimalField(blank=True, decimal_places=2, help_text='0.00 a 1.00', max_digits=3, null=True, verbose_name='risco de churn')),
                ('predicted_ltv_q', models.BigIntegerField(blank=True, help_text='LTV previsto em centavos', null=True, verbose_name='LTV previsto (centavos)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='calculado em')),
                ('calculation_version', models.CharField(default='v1', help_text='Versão do algoritmo de cálculo', max_length=20, verbose_name='versão do cálculo')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='guestman.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'insight do cliente',
                'verbose_name_plural': 'insights dos clientes',
            },
        ),
    ]
