# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text='Referência única do cliente (ex: CLI-001)', max_length=50, unique=True, verbose_name='referência')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='sobrenome')),
                ('customer_type', models.CharField(choices=[('individual', 'Pessoa Física'), ('business', 'Pessoa Jurídica')], default='individual', max_length=20, verbose_name='tipo')),
                ('document', models.CharField(blank=True, db_index=True, help_text='CPF ou CNPJ (apenas números)', max_length=20, verbose_name='documento')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='telefone')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados do cliente. Ex: {"preferences": "sem lactose", "birthday": "1990-05-15"}', verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='criado por')),
                ('source_system', models.CharField(blank=True, max_length=100, verbose_name='sistema de origem')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(unique=True, verbose_name='referência')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('listing_ref', models.CharField(blank=True, help_text='Código do Listing no Offering (convenção: Listing.ref == Channel.ref)', max_length=50, verbose_name='código da listagem')),
                ('is_default', models.BooleanField(default=False, help_text='Grupo padrão para novos clientes', verbose_name='padrão')),
                ('priority', models.IntegerField(default=0, help_text='Maior = mais prioridade', verbose_name='prioridade')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados do grupo. Ex: {"discount_percent": 10, "min_order_q": 5000}', verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'grupo de clientes',
                'verbose_name_plural': 'grupos de clientes',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('home', 'Casa'), ('work', 'Trabalho'), ('other', 'Outro')], default='home', max_length=20, verbose_name='rótulo')),
                ('label_custom', models.CharField(blank=True, help_text='Rótulo personalizado quando tipo=outro', max_length=50, verbose_name='rótulo personalizado')),
                ('place_id', models.CharField(blank=True, help_text='ID do Google Places', max_length=255, verbose_name='ID do Google Places')),
                ('formatted_address', models.CharField(help_text='Endereço completo formatado', max_length=500, verbose_name='endereço formatado')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('route', models.CharField(blank=True, help_text='Nome da rua', max_length=200, verbose_name='logradouro')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='estado')),
                ('state_code', models.CharField(blank=True, help_text='Sigla do estado', max_length=5, verbose_name='UF')),
                ('postal_code', models.CharField(blank=True, help_text='Código postal', max_length=20, verbose_name='CEP')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='país')),
                ('country_code', models.CharField(default='BR', max_length=5, verbose_name='código do país')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('complement', models.CharField(blank=True, help_text='Apto, bloco, referência', max_length=100, verbose_name='complemento')),
                ('delivery_instructions', models.TextField(blank=True, help_text='Instruções para o entregador', verbose_name='instruções de entrega')),
                ('is_default', models.BooleanField(default=False, verbose_name='padrão')),
                ('is_verified', models.BooleanField(default=False, help_text='Endereço verificado via Google Places', verbose_name='verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='guestman.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'ordering': ['-is_default', 'label'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='guestman.customergroup', verbose_name='grupo'),
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('manychat', 'ManyChat'), ('whatsapp', 'WhatsApp Business'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google', 'Google'), ('apple', 'Apple'), ('telegram', 'Telegram'), ('other', 'Outro')], max_length=20, verbose_name='provedor')),
                ('provider_uid', models.CharField(help_text='ID único no provedor (ex: Manychat subscriber_id)', max_length=255, verbose_name='ID no provedor')),
                ('provider_meta', models.JSONField(blank=True, default=dict, help_text='Dados do provedor externo. Ex: {"wa_id": "5543...", "ig_scoped_id": "abc123"}', verbose_name='metadados do provedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='guestman.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'identidade externa',
                'verbose_name_plural': 'identidades externas',
                'db_table': 'customers_external_identity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='nonce')),
                ('provider', models.CharField(db_index=True, max_length=50, verbose_name='provedor')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='processado em')),
            ],
            options={
                'verbose_name': 'evento processado',
                'verbose_name_plural': 'eventos processados',
                'db_table': 'customers_processed_event',
                'indexes': [models.Index(fields=['provider', 'processed_at'], name='customers_p_provide_6ee46f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Telefone (voz/SMS)'), ('email', 'Email'), ('instagram', 'Instagram')], max_length=20, verbose_name='tipo')),
                ('value_normalized', models.CharField(db_index=True, help_text='Telefone em E.164 (+5541999998888) ou email em minúsculas.', max_length=255, verbose_name='valor normalizado')),
                ('value_display', models.CharField(blank=True, help_text='Formato amigável para exibição.', max_length=255, verbose_name='valor para exibição')),
                ('is_primary', models.BooleanField(default=False, verbose_name='principal')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verificado')),
                ('verification_method', models.CharField(choices=[('unverified', 'Não verificado'), ('channel_asserted', 'Verificado pelo canal'), ('otp_whatsapp', 'OTP via WhatsApp'), ('otp_sms', 'OTP via SMS'), ('email_link', 'Link por email'), ('manual', 'Manual (equipe)')], default='unverified', max_length=20, verbose_name='método de verificação')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('verification_ref', models.CharField(blank=True, help_text='Referência externa (ex: Manychat subscriber_id).', max_length=255, verbose_name='referência de verificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='guestman.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'db_table': 'customers_contact_point',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'type', 'is_primary'], name='customers_c_custome_3b178c_idx'), models.Index(fields=['type', 'value_normalized'], name='customers_c_type_197768_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'value_normalized'), name='guestman_unique_contact_value'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('customer', 'type'), name='guestman_unique_primary_per_type')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['ref'], name='guestman_cu_ref_96de55_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['document'], name='guestman_cu_documen_5865dc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='guestman_cu_phone_5795fb_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='guestman_cu_email_3d18f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='unique_customer_phone'),
        ),
        migrations.AddIndex(
            model_name='externalidentity',
            index=models.Index(fields=['customer', 'provider'], name='customers_e_custome_311efb_idx'),
        ),
        migrations.AddIndex(
            model_name='externalidentity',
            index=models.Index(fields=['provider', 'provider_uid'], name='customers_e_provide_fa1ca5_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_uid'), name='guestman_unique_external_identity'),
        ),
    ]
