# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('phone', 'Telefone'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('manychat', 'Manychat ID'), ('cpf', 'CPF'), ('ifood', 'iFood')], max_length=20, verbose_name='tipo')),
                ('identifier_value', models.CharField(help_text='Valor normalizado (telefone sem formatação, email minúsculo)', max_length=255, verbose_name='valor')),
                ('is_primary', models.BooleanField(default=False, help_text='Identificador principal deste tipo', verbose_name='principal')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Quando foi verificado (ex: OTP)', null=True, verbose_name='verificado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('source_system', models.CharField(blank=True, max_length=100, verbose_name='sistema de origem')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='guestman.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'identificador',
                'verbose_name_plural': 'identificadores',
                'indexes': [models.Index(fields=['identifier_type', 'identifier_value'], name='guestman_id_identif_78db49_idx')],
                'constraints': [models.UniqueConstraint(fields=('identifier_type', 'identifier_value'), name='guestman_unique_identifier')],
            },
        ),
    ]
